### PR TITLE
add admin interface

### PR DESCRIPTION
**Pull request by GV14982**
- Added queries and migrations and api routes
- Added tables and ability to add a new encounter and reward

### CODE REVIEW

**Review by seanmetzgar — COMMENTED** [review]
heyo, let's go over this tomorrow or monday at some point. I want to get on board to make sure we are using the same paths/page name structure :)

**Comment by cvasquez** [comment]
@GV14982 Looking great!
Things that need to happen before we can merge:

- Add ability to edit encounters.
- Add ability to delete encounters.
- Add ability to add thumbnails to encounters.
- Make "Reward" a required field in encounter creation.

**Comment by GV14982** [comment]
After checking this out with @cvasquez, I realized I'm not flushing the data in the `newEncounter` state object. So if you edit an entry, the try and create one, it will just edit the one you just had open.

I just need to add some code to reset the `newEncounter` state to a default value when the modal is closed.

**Comment by GV14982** [comment]
Alright I'm just merging this.

**Pull request merged**
